packages:
  - next
  - empty
  - hono
  - preact-spa

catalogs:
  deps:
    '@google-cloud/vision': ^4.0.3
    '@jokester/ts-commonutil': ^0.6.1
    '@slack/bolt': ^4.4.0
    '@slack/web-api': ^7.9.3
    '@slack/webhook': ^7.0.5
    '@swc/wasm': ^1.13.3
    '@swc/wasm-typescript': ^1.13.3
    '@zip.js/zip.js': ^2.7.34
    date-fns: ^3
    debug: ^4.4.1
    dotenv: ^17.0.1
    drizzle-orm: ^0.44.2
    jotai: ^2.12.3
    lodash-es: ^4.17.21
    openai: ^4.27.0
    really-relaxed-json: ^0.3.2
    streamlit-component-lib: ^2.0.0
    superjson: ^2.2.1
    valtio: ^2.1.4
    zod: ^3.23
    zustand: ^5.0.3
  deps-hono:
    '@hono/node-server': ^1.17.1
    hono: ^4.8.10
  deps-react:
    '@chakra-ui/react': ^2.8.2
    '@emotion/react': ^11.11.3
    '@emotion/styled': ^11.11.0
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-select': ^2.2.5
    '@radix-ui/react-slot': ^1.2.3
    '@trpc/client': ^10.45.2
    '@trpc/next': ^10.45.2
    '@trpc/server': ^10.45.2
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    foxact: ^0.2.49
    framer-motion: ^11.0.5
    lucide-react: ^0.534.0
    next: ^14.2.30
    preact: ^10.27.0
    preact-router: ^4.1.2
    primereact: ^10.9.6
    react: ^19.1.1
    react-dom: ^19.1.1
    tailwind-merge: ^3.3.1
  dev-deps:
    '@cloudflare/workers-types': ^4.20250704.0
    '@eslint-react/eslint-plugin': ^1.52.3
    '@eslint/js': ^9.32.0
    '@next/bundle-analyzer': ^14.2.18
    '@next/eslint-plugin-next': ^14.2.18
    '@preact/preset-vite': ^2.10.2
    '@swc-node/jest': ^1.8.13
    '@tailwindcss/vite': ^4.1.11
    '@tsconfig/strictest': ^2.0.5
    '@types/better-sqlite3': ^7.6.13
    '@types/debug': ^4.1.12
    '@types/jest': ^30
    '@types/lodash-es': ^4.17.12
    '@types/node': ^22.17.0
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
    '@types/serve-handler': ^6.1.4
    '@vitejs/plugin-react': ^4.7.0
    '@wxt-dev/module-react': ^1.1.3
    '@tailwindcss/postcss': ^4.1.11
    autoprefixer: ^10.4.21
    better-sqlite3: ^12.2.0
    dprint: ^0.50.1
    drizzle-kit: ^0.31.4
    eslint: ^9.32.0
    eslint-plugin-import-x: ^4.16.1
    jest: ^30
    postcss: ^8.5.6
    rollup-plugin-visualizer: ^6.0.3
    sass: ^1.89.2
    tailwindcss: ^4.1.11
    tslib: ^2.8.1
    tsx: ^4.20.3
    tw-animate-css: ^1.3.6
    typescript: ^5.8.3
    typescript-eslint: ^8.38.0
    vite: ^7.0.6
    wrangler: ^3.114.10
    wxt: ^0.20.7

onlyBuiltDependencies:
  - '@swc/core'
